---
title: "Intención de voto elecciones presidenciales Colombia 2022"
subtitle: "Exploración estadística"
author: "Edimer David Jaramillo"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float:
      smooth_scroll: false
      collapsed: false
    df_print: paged
    code_folding: hide
    css: estilo.css 
    theme: cosmo
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE, fig.align = "center")

library(tidyverse)
library(readxl)
library(janitor)
library(DT)
library(rvest)
library(lubridate)
library(cowplot)
library(ggsci)
library(splines)
library(qqplotr)
library(broom)
library(infer)
library(plotly)

source("../functions-R/plot_distribution.R", encoding = "UTF-8")
source("../functions-R/plot_time.R", encoding = "UTF-8")
source("../functions-R/plot_cor.R", encoding = "UTF-8")
source("../functions-R/plot_scatter.R", encoding = "UTF-8")
source("../functions-R/plot_encuestas.R", encoding = "UTF-8")

theme_set(theme_minimal())
```

# Bibliotecas

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(DT)
library(rvest)
library(lubridate)
library(cowplot)
library(ggsci)
library(splines)
library(qqplotr)
library(broom)
library(infer)
library(plotly)
```

# Funciones

```{r}
source("../functions-R/plot_distribution.R", encoding = "UTF-8")
source("../functions-R/plot_time.R", encoding = "UTF-8")
source("../functions-R/plot_cor.R", encoding = "UTF-8")
source("../functions-R/plot_scatter.R", encoding = "UTF-8")
source("../functions-R/plot_encuestas.R", encoding = "UTF-8")
```


# Datos

```{r}
datos <- read_csv("../data/EncuestasColombia2022-Update.csv") %>%
  mutate(
    encuesta = str_to_lower(encuesta),
    encuesta = str_to_sentence(encuesta),
    encuesta = if_else(
      str_detect(encuesta, "Cnc"),
      true = "Cnc",
      false = encuesta
    ),
    encuesta = if_else(
      str_detect(encuesta, "Mosqueteros"),
      true = "Mosqueteros",
      false = encuesta
    )
  )

candidatos <- datos %>% 
  select(where(is.numeric)) %>% 
  select(-c(tamano_de_muestra, margen_de_error)) %>% 
  names()

datos
```

# Exploratorio

## Intención de voto

### Distribuciones

```{r}
plot_distribution(data = datos, agrupado = TRUE, tipo = "boxplot",
                  candidato = "sergio_fajardo")
```

### Variación temporal

```{r}
plot_time(data = datos,
          tipo = "Serie Individual",
          candidato = "gustavo_petro")
```

### Correlaciones

```{r}
datos %>% 
  plot_cor()
```

### Dispersión

```{r}
datos %>% 
  plot_scatter(data = ., candidato_x = "gustavo_petro", candidato_y = "sergio_fajardo")
```

## Firmas encuestadoras

```{r}
plot_encuestas(tipo = "Total Encuestas")
```

